### ISSUE TITLE
Improve the review comments workflow

### ISSUE THREAD

**Issue by carletex** [moonshotcollective/scaffold-directory#123]
This issue has multiple tasks and we might want to broke them down into several PR.

- [x] 1. On the "Review submissions" page, allow expanding the textarea. Fixed on #127

![image](https://user-images.githubusercontent.com/2486142/144511512-e8741c33-53dc-4198-8a8e-ad217335a5d5.png)

We could merge the contract & live demo columns, expand the textarea a bit, and add a "expand icon". When clicking the icon, show a big modal with a textarea.

Another option would be to remove the textarea from the row and show it in a modal when clicking approve / reject. Fill it and confirm.

- [x] Moved to #131

- [x] 3. When a builder resubmit, show the previous reviewMessage. To do this, on the backend, we should detect that the user is re-submitting and pass along the existing reviewMessage. Fixed on #128 

- [x] 4. Since we expect bigger review messages, we want to show them in a different way in the builder profile view. Right now it's just a tooltip when hovering the question mark icon. Fixed on #130 

![photo1638260183](https://user-images.githubusercontent.com/2486142/144513561-c15444e7-da17-4797-b02b-6cfe9ee11ef9.jpeg)

We could add a down arrow icon (instead of a question mark) and make it behave like an accordion, showing the review comment when clicking the icon.

- [x] 5. We are currently only showing the rejected review messages. Also show the approved review messages. Fixed on #130
